export const currencies = [
    { code: 'USD', label: 'USD - US Dollar ($)', symbol: '$' },
    { code: 'EUR', label: 'EUR - Euro (€)', symbol: '€' },
    { code: 'GBP', label: 'GBP - British Pound (£)', symbol: '£' },
    { code: 'INR', label: 'INR - Indian Rupee (₹)', symbol: '₹' },
    { code: 'JPY', label: 'JPY - Japanese Yen (¥)', symbol: '¥' },
    { code: 'CNY', label: 'CNY - Chinese Yuan (¥)', symbol: '¥' },
    { code: 'AUD', label: 'AUD - Australian Dollar ($)', symbol: 'A$' },
    { code: 'CAD', label: 'CAD - Canadian Dollar ($)', symbol: 'C$' },
    { code: 'CHF', label: 'CHF - Swiss Franc (Fr)', symbol: 'Fr' },
    { code: 'HKD', label: 'HKD - Hong Kong Dollar ($)', symbol: 'HK$' },
    { code: 'SGD', label: 'SGD - Singapore Dollar ($)', symbol: 'S$' },
    { code: 'AED', label: 'AED - United Arab Emirates Dirham (د.إ)', symbol: 'د.إ' },
    { code: 'PKR', label: 'PKR - Pakistani Rupee (Rs)', symbol: 'Rs' },
    { code: 'AFN', label: 'AFN - Afghan Afghani (؋)', symbol: '؋' },
    { code: 'ALL', label: 'ALL - Albanian Lek (L)', symbol: 'L' },
    { code: 'AMD', label: 'AMD - Armenian Dram (֏)', symbol: '֏' },
    { code: 'ANG', label: 'ANG - Netherlands Antillean Guilder (ƒ)', symbol: 'ƒ' },
    { code: 'AOA', label: 'AOA - Angolan Kwanza (Kz)', symbol: 'Kz' },
    { code: 'ARS', label: 'ARS - Argentine Peso ($)', symbol: 'AR$' },
    { code: 'AWG', label: 'AWG - Aruban Florin (ƒ)', symbol: 'ƒ' },
    { code: 'AZN', label: 'AZN - Azerbaijani Manat (₼)', symbol: '₼' },
    { code: 'BAM', label: 'BAM - Bosnia-Herzegovina Convertible Mark (KM)', symbol: 'KM' },
    { code: 'BBD', label: 'BBD - Barbadian Dollar ($)', symbol: 'Bds$' },
    { code: 'BDT', label: 'BDT - Bangladeshi Taka (৳)', symbol: '৳' },
    { code: 'BGN', label: 'BGN - Bulgarian Lev (лв)', symbol: 'лв' },
    { code: 'BHD', label: 'BHD - Bahraini Dinar (.د.ب)', symbol: '.د.ب' },
    { code: 'BIF', label: 'BIF - Burundian Franc (FBu)', symbol: 'FBu' },
    { code: 'BMD', label: 'BMD - Bermudan Dollar ($)', symbol: 'BD$' },
    { code: 'BND', label: 'BND - Brunei Dollar ($)', symbol: 'B$' },
    { code: 'BOB', label: 'BOB - Bolivian Boliviano (Bs.)', symbol: 'Bs.' },
    { code: 'BRL', label: 'BRL - Brazilian Real (R$)', symbol: 'R$' },
    { code: 'BSD', label: 'BSD - Bahamian Dollar ($)', symbol: 'B$' },
    { code: 'BTN', label: 'BTN - Bhutanese Ngultrum (Nu.)', symbol: 'Nu.' },
    { code: 'BWP', label: 'BWP - Botswanan Pula (P)', symbol: 'P' },
    { code: 'BYN', label: 'BYN - Belarusian Ruble (Br)', symbol: 'Br' },
    { code: 'BZD', label: 'BZD - Belize Dollar ($)', symbol: 'BZ$' },
    { code: 'CDF', label: 'CDF - Congolese Franc (FC)', symbol: 'FC' },
    { code: 'CLP', label: 'CLP - Chilean Peso ($)', symbol: 'CL$' },
    { code: 'COP', label: 'COP - Colombian Peso ($)', symbol: 'COL$' },
    { code: 'CRC', label: 'CRC - Costa Rican Colón (₡)', symbol: '₡' },
    { code: 'CUP', label: 'CUP - Cuban Peso ($)', symbol: '$' },
    { code: 'CVE', label: 'CVE - Cape Verdean Escudo ($)', symbol: '$' },
    { code: 'CZK', label: 'CZK - Czech Koruna (Kč)', symbol: 'Kč' },
    { code: 'DJF', label: 'DJF - Djiboutian Franc (Fdj)', symbol: 'Fdj' },
    { code: 'DKK', label: 'DKK - Danish Krone (kr)', symbol: 'kr' },
    { code: 'DOP', label: 'DOP - Dominican Peso ($)', symbol: 'RD$' },
    { code: 'DZD', label: 'DZD - Algerian Dinar (د.ج)', symbol: 'د.ج' },
    { code: 'EGP', label: 'EGP - Egyptian Pound (E£)', symbol: 'E£' },
    { code: 'ERN', label: 'ERN - Eritrean Nakfa (Nfk)', symbol: 'Nfk' },
    { code: 'ETB', label: 'ETB - Ethiopian Birr (Br)', symbol: 'Br' },
    { code: 'FJD', label: 'FJD - Fijian Dollar ($)', symbol: 'FJ$' },
    { code: 'FKP', label: 'FKP - Falkland Islands Pound (£)', symbol: '£' },
    { code: 'GEL', label: 'GEL - Georgian Lari (₾)', symbol: '₾' },
    { code: 'GHS', label: 'GHS - Ghanaian Cedi (₵)', symbol: '₵' },
    { code: 'GIP', label: 'GIP - Gibraltar Pound (£)', symbol: '£' },
    { code: 'GMD', label: 'GMD - Gambian Dalasi (D)', symbol: 'D' },
    { code: 'GNF', label: 'GNF - Guinean Franc (FG)', symbol: 'FG' },
    { code: 'GTQ', label: 'GTQ - Guatemalan Quetzal (Q)', symbol: 'Q' },
    { code: 'GYD', label: 'GYD - Guyanaese Dollar ($)', symbol: 'G$' },
    { code: 'HNL', label: 'HNL - Honduran Lempira (L)', symbol: 'L' },
    { code: 'HRK', label: 'HRK - Croatian Kuna (kn)', symbol: 'kn' },
    { code: 'HTG', label: 'HTG - Haitian Gourde (G)', symbol: 'G' },
    { code: 'HUF', label: 'HUF - Hungarian Forint (Ft)', symbol: 'Ft' },
    { code: 'IDR', label: 'IDR - Indonesian Rupiah (Rp)', symbol: 'Rp' },
    { code: 'ILS', label: 'ILS - Israeli New Shekel (₪)', symbol: '₪' },
    { code: 'IQD', label: 'IQD - Iraqi Dinar (د.ع)', symbol: 'د.ع' },
    { code: 'IRR', label: 'IRR - Iranian Rial (﷼)', symbol: '﷼' },
    { code: 'ISK', label: 'ISK - Icelandic Króna (kr)', symbol: 'kr' },
    { code: 'JMD', label: 'JMD - Jamaican Dollar ($)', symbol: 'J$' },
    { code: 'JOD', label: 'JOD - Jordanian Dinar (د.ا)', symbol: 'د.ا' },
    { code: 'KES', label: 'KES - Kenyan Shilling (KSh)', symbol: 'KSh' },
    { code: 'KGS', label: 'KGS - Kyrgystani Som (с)', symbol: 'с' },
    { code: 'KHR', label: 'KHR - Cambodian Riel (៛)', symbol: '៛' },
    { code: 'KMF', label: 'KMF - Comorian Franc (CF)', symbol: 'CF' },
    { code: 'KPW', label: 'KPW - North Korean Won (₩)', symbol: '₩' },
    { code: 'KRW', label: 'KRW - South Korean Won (₩)', symbol: '₩' },
    { code: 'KWD', label: 'KWD - Kuwaiti Dinar (د.ك)', symbol: 'د.ك' },
    { code: 'KYD', label: 'KYD - Cayman Islands Dollar ($)', symbol: 'CI$' },
    { code: 'KZT', label: 'KZT - Kazakhstani Tenge (₸)', symbol: '₸' },
    { code: 'LAK', label: 'LAK - Laotian Kip (₭)', symbol: '₭' },
    { code: 'LBP', label: 'LBP - Lebanese Pound (L£)', symbol: 'L£' },
    { code: 'LKR', label: 'LKR - Sri Lankan Rupee (Rs)', symbol: 'Rs' },
    { code: 'LRD', label: 'LRD - Liberian Dollar ($)', symbol: 'L$' },
    { code: 'LSL', label: 'LSL - Lesotho Loti (L)', symbol: 'L' },
    { code: 'LYD', label: 'LYD - Libyan Dinar (د.ل)', symbol: 'د.ل' },
    { code: 'MAD', label: 'MAD - Moroccan Dirham (د.م.)', symbol: 'د.م.' },
    { code: 'MDL', label: 'MDL - Moldovan Leu (L)', symbol: 'L' },
    { code: 'MGA', label: 'MGA - Malagasy Ariary (Ar)', symbol: 'Ar' },
    { code: 'MKD', label: 'MKD - Macedonian Denar (ден)', symbol: 'ден' },
    { code: 'MMK', label: 'MMK - Myanmar Kyat (K)', symbol: 'K' },
    { code: 'MNT', label: 'MNT - Mongolian Tugrik (₮)', symbol: '₮' },
    { code: 'MOP', label: 'MOP - Macanese Pataca (P)', symbol: 'P' },
    { code: 'MRU', label: 'MRU - Mauritanian Ouguiya (UM)', symbol: 'UM' },
    { code: 'MUR', label: 'MUR - Mauritian Rupee (Rs)', symbol: 'Rs' },
    { code: 'MVR', label: 'MVR - Maldivian Rufiyaa (Rf)', symbol: 'Rf' },
    { code: 'MWK', label: 'MWK - Malawian Kwacha (MK)', symbol: 'MK' },
    { code: 'MXN', label: 'MXN - Mexican Peso ($)', symbol: 'Mex$' },
    { code: 'MYR', label: 'MYR - Malaysian Ringgit (RM)', symbol: 'RM' },
    { code: 'MZN', label: 'MZN - Mozambican Metical (MT)', symbol: 'MT' },
    { code: 'NAD', label: 'NAD - Namibian Dollar ($)', symbol: 'N$' },
    { code: 'NGN', label: 'NGN - Nigerian Naira (₦)', symbol: '₦' },
    { code: 'NIO', label: 'NIO - Nicaraguan Córdoba (C$)', symbol: 'C$' },
    { code: 'NOK', label: 'NOK - Norwegian Krone (kr)', symbol: 'kr' },
    { code: 'NPR', label: 'NPR - Nepalese Rupee (Rs)', symbol: 'Rs' },
    { code: 'NZD', label: 'NZD - New Zealand Dollar ($)', symbol: 'NZ$' },
    { code: 'OMR', label: 'OMR - Omani Rial (ر.ع.)', symbol: 'ر.ع.' },
    { code: 'PAB', label: 'PAB - Panamanian Balboa (B/.)', symbol: 'B/.' },
    { code: 'PEN', label: 'PEN - Peruvian Sol (S/.)', symbol: 'S/.' },
    { code: 'PGK', label: 'PGK - Papua New Guinean Kina (K)', symbol: 'K' },
    { code: 'PHP', label: 'PHP - Philippine Peso (₱)', symbol: '₱' },
    { code: 'PLN', label: 'PLN - Polish Zloty (zł)', symbol: 'zł' },
    { code: 'PYG', label: 'PYG - Paraguayan Guarani (₲)', symbol: '₲' },
    { code: 'QAR', label: 'QAR - Qatari Rial (ر.ق)', symbol: 'ر.ق' },
    { code: 'RON', label: 'RON - Romanian Leu (lei)', symbol: 'lei' },
    { code: 'RSD', label: 'RSD - Serbian Dinar (din)', symbol: 'din' },
    { code: 'RUB', label: 'RUB - Russian Ruble (₽)', symbol: '₽' },
    { code: 'RWF', label: 'RWF - Rwandan Franc (FRw)', symbol: 'FRw' },
    { code: 'SAR', label: 'SAR - Saudi Riyal (ر.س)', symbol: 'ر.س' },
    { code: 'SBD', label: 'SBD - Solomon Islands Dollar ($)', symbol: 'SI$' },
    { code: 'SCR', label: 'SCR - Seychellois Rupee (Rs)', symbol: 'Rs' },
    { code: 'SDG', label: 'SDG - Sudanese Pound (S£)', symbol: 'S£' },
    { code: 'SEK', label: 'SEK - Swedish Krona (kr)', symbol: 'kr' },
    { code: 'SHP', label: 'SHP - St. Helena Pound (£)', symbol: '£' },
    { code: 'SLL', label: 'SLL - Sierra Leonean Leone (Le)', symbol: 'Le' },
    { code: 'SOS', label: 'SOS - Somali Shilling (Sh)', symbol: 'Sh' },
    { code: 'SRD', label: 'SRD - Surinamese Dollar ($)', symbol: 'Sur$' },
    { code: 'SSP', label: 'SSP - South Sudanese Pound (S£)', symbol: 'S£' },
    { code: 'STN', label: 'STN - São Tomé & Príncipe Dobra (Db)', symbol: 'Db' },
    { code: 'SYP', label: 'SYP - Syrian Pound (LS)', symbol: 'LS' },
    { code: 'SZL', label: 'SZL - Swazi Lilangeni (L)', symbol: 'L' },
    { code: 'THB', label: 'THB - Thai Baht (฿)', symbol: '฿' },
    { code: 'TJS', label: 'TJS - Tajikistani Somoni (ЅМ)', symbol: 'ЅМ' },
    { code: 'TMT', label: 'TMT - Turkmenistani Manat (m)', symbol: 'm' },
    { code: 'TND', label: 'TND - Tunisian Dinar (د.ت)', symbol: 'د.ت' },
    { code: 'TOP', label: 'TOP - Tongan Paʻanga (T$)', symbol: 'T$' },
    { code: 'TRY', label: 'TRY - Turkish Lira (₺)', symbol: '₺' },
    { code: 'TTD', label: 'TTD - Trinidad & Tobago Dollar ($)', symbol: 'TT$' },
    { code: 'TWD', label: 'TWD - New Taiwan Dollar ($)', symbol: 'NT$' },
    { code: 'TZS', label: 'TZS - Tanzanian Shilling (TSh)', symbol: 'TSh' },
    { code: 'UAH', label: 'UAH - Ukrainian Hryvnia (₴)', symbol: '₴' },
    { code: 'UGX', label: 'UGX - Ugandan Shilling (USh)', symbol: 'USh' },
    { code: 'UYU', label: 'UYU - Uruguayan Peso ($)', symbol: '$U' },
    { code: 'UZS', label: 'UZS - Uzbekistani Som (с)', symbol: 'с' },
    { code: 'VES', label: 'VES - Venezuelan Bolívar (Bs.S)', symbol: 'Bs.S' },
    { code: 'VND', label: 'VND - Vietnamese Dong (₫)', symbol: '₫' },
    { code: 'VUV', label: 'VUV - Vanuatu Vatu (VT)', symbol: 'VT' },
    { code: 'WST', label: 'WST - Samoan Tala (WS$)', symbol: 'WS$' },
    { code: 'XAF', label: 'XAF - Central African CFA Franc (FCFA)', symbol: 'FCFA' },
    { code: 'XCD', label: 'XCD - East Caribbean Dollar ($)', symbol: 'EC$' },
    { code: 'XOF', label: 'XOF - West African CFA Franc (CFA)', symbol: 'CFA' },
    { code: 'XPF', label: 'XPF - CFP Franc (CFP)', symbol: 'CFP' },
    { code: 'YER', label: 'YER - Yemeni Rial (﷼)', symbol: '﷼' },
    { code: 'ZAR', label: 'ZAR - South African Rand (R)', symbol: 'R' },
    { code: 'ZMW', label: 'ZMW - Zambian Kwacha (ZK)', symbol: 'ZK' },
    { code: 'ZWL', label: 'ZWL - Zimbabwean Dollar ($)', symbol: 'Z$' },
];
